# Generated by Django 4.0 on 2023-08-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Enter a user login', max_length=255, verbose_name='User login')),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(help_text='Enter a user password', max_length=255, verbose_name='User password')),
            ],
        ),
    ]
