# Generated by Django 4.0 on 2023-09-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_users_options_alter_users_mail'),
        ('tasks', '0002_alter_tasks_options_alter_tasks_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter a comment', max_length=3000, verbose_name='Comment')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comments')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_task', to='tasks.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to='users.users')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ('-date_creation',),
            },
        ),
    ]
