# Generated by Django 4.0 on 2023-08-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a task name', max_length=255, verbose_name='Task name')),
                ('description', models.TextField(help_text='Enter a task description', max_length=3000, verbose_name='Task description')),
                ('status', models.CharField(choices=[('1', 'В ожидании'), ('2', 'В процессе'), ('3', 'Завершено')], default='В ожидании', max_length=11)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
